connection:
  web:
    type: web
    default_element_wait: 60

  n1:
    prompt: ['~ #', '#', '>']
    ip: 10.5.161.154
    port: 4015
    protocol: telnet
    timeout: 5
    type: linux
    user: admin
    password: admin
    login_prompt: 'User Name'
    password_prompt: 'Password'
    
  cisco:
    prompt: ['dhcpv6>', 'dhcpv6#', 'dhcpv6(config)#', 'dhcpv6(config-if-range)#', 'dhcpv6(config-line)#']
    ip: 10.5.161.154
    port: 4017
    protocol: telnet
    timeout: 5
    type: linux

  cisco_ip_server:
    prompt: ['C1800-DHCP>', 'C1800-DHCP#', 'C1800-DHCP(config)#', 'C1800-DHCP(config-if-range)#', 'C1800-DHCP(config-line)#']
    ip: 10.5.161.154
    port: 4019
    protocol: telnet
    timeout: 5
    type: linux

  wifi_client:
    ip: 10.5.161.101
    type: linux
    protocol: ssh
    user: vagrant
    password: vagrant
    prompt: ['vagrant\@thomas-VPCEB37FW\:\~\$']

